### ISSUE TITLE
Need to generate better ids for respec sections

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#375]
Now, bikeshed section ids are autogenerated. However, the algorithm does not work well with diacritics, resulting e.g. in
`documentation.html#pevod-innosti` instead of e.g. `documentation.html#převod-činnosti`. These IDs need to be inserted extra like this:
```
Úvod {#úvod}
============

#### Vazba: Obor hodnot vztahu #### {#vazba-konceptuální-model-vztah-obor-hodnot}
```

**Comment by sstenchlak** [comment]
It has already been fixed in 534fefab8f9cebbe249063fcc52c481ce2e2cb35.

**Comment by jakubklimek** [comment]
Actually, I still get e.g. 
- "#produkt-i-sluba-vyuvajc-oteven-data" with the czech characters removed
-  or "#conceptual-class-katalogizovany-zdroj" - here, in a czech documentation, I would expect "třída", not "conceptual class" (this means configuration option) and I would expect to keep the diacritics.

Since we are migrating to Respec, I am not sure how relevant this is - i.e. whether the same thing needs to be dealt with also in Respec. If irrelevant, feel free to close.

**Comment by jakubklimek** [comment]
The ID's are still incorrect in Respec, e.g. `#json-structure-property-datum-a-cas`.
We need
1. to keep unicode characters from the label
2. have language variants for `json-structure` etc.
3. be able to decide which language version of the documentation I want to generate, possibly multiple ones.

**Comment by jakubklimek** [comment]
Actually, there are still errors with this - see Údaj in https://pod-test.dia.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/datové-sady-publikující-údaje/2024-02-28/#conceptual-class-udaj
![image](https://github.com/mff-uk/dataspecer/assets/718827/43a60cdd-5e60-451d-bcdf-9f1e67a757ea)

Points to `#conceptual-class-udaj` instead of `#konceptuální-třída-údaj`
